var app = angular.module("myApp", ["ngRoute"]);
    app.config(function($routeProvider)
    {
            $routeProvider
            .when("/rideslide",
            {
                templateUrl:"rideslide.html",
                controller:"myCtrl"
            })
            .when("/rideslide2",
            {
                templateUrl:"rideslide2.html",
                controller:"myCtrl"
            })
            .when("/information",
            {
                templateUrl:"information.html",
                controller:"myCtrl"
            })
            .when("/information2",
            {
                templateUrl:"information2.html",
                controller:"myCtrl"
            })
            .when("/facilities",
            {
                templateUrl:"facilities.html",
                controller:"myCtrl"
            })
            .when("/food",
            {
                templateUrl:"food.html",
                controller:"myCtrl"
            })
            .when("/contactus",
            {
                templateUrl:"contactus.html",
                controller:"myCtrl"
            })
            .when("/map",
            {
                templateUrl:"map.html",
                controller:"myCtrl"
            })
            .when("/aboutus",
            {
                templateUrl:"aboutus.html",
                controller:"myCtrl"
            }) ;
    });
   