var app = angular.module("myApp", ["ngRoute"]);
    app.config(function($routeProvider)
    {
            $routeProvider
            .when("/rideslide",
            {
                templateUrl:"rideslide.html",
                controller:"myCtrl"
            })
            .when("/rideslide3",
            {
                templateUrl:"rideslide3.html",
                controller:"myCtrl"
            })
            .when("/rideslide4",
            {
                templateUrl:"rideslide4.html",
                controller:"myCtrl"
            })
            .when("/rideslide5",
            {
                templateUrl:"rideslide5.html",
                controller:"myCtrl"
            })
            .when("/rideslide6",
            {
                templateUrl:"rideslide6.html",
                controller:"myCtrl"
            })
            .when("/rideslide7",
            {
                templateUrl:"rideslide7.html",
                controller:"myCtrl"
            })
            .when("/rideslide8",
            {
                templateUrl:"rideslide8.html",
                controller:"myCtrl"
            })
            .when("/rideslide9",
            {
                templateUrl:"rideslide9.html",
                controller:"myCtrl"
            })
            .when("/rideslide10",
            {
                templateUrl:"rideslide10.html",
                controller:"myCtrl"
            })
            .when("/rideslide11",
            {
                templateUrl:"rideslide11.html",
                controller:"myCtrl"
            })
            .when("/information",
            {
                templateUrl:"information.html",
                controller:"myCtrl"
            })
            .when("/information2",
            {
                templateUrl:"information2.html",
                controller:"myCtrl"
            })
            .when("/information3",
            {
                templateUrl:"information3.html",
                controller:"myCtrl"
            })
            .when("/information4",
            {
                templateUrl:"information4.html",
                controller:"myCtrl"
            })
            .when("/information5",
            {
                templateUrl:"information5.html",
                controller:"myCtrl"
            })
            .when("/information6",
            {
                templateUrl:"information6.html",
                controller:"myCtrl"
            })
            .when("/information7",
            {
                templateUrl:"information7.html",
                controller:"myCtrl"
            })
            .when("/information8",
            {
                templateUrl:"information8.html",
                controller:"myCtrl"
            })
            .when("/information9",
            {
                templateUrl:"information9.html",
                controller:"myCtrl"
            })
            .when("/facilities",
            {
                templateUrl:"facilities.html",
                controller:"myCtrl"
            })
            .when("/food",
            {
                templateUrl:"food.html",
                controller:"myCtrl"
            })
            .when("/food2",
            {
                templateUrl:"food2.html",
                controller:"myCtrl"
            })
            .when("/food3",
            {
                templateUrl:"food3.html",
                controller:"myCtrl"
            })
            .when("/food4",
            {
                templateUrl:"food4.html",
                controller:"myCtrl"
            })
            .when("/food5",
            {
                templateUrl:"food5.html",
                controller:"myCtrl"
            })
            .when("/food6",
            {
                templateUrl:"food6.html",
                controller:"myCtrl"
            })
            .when("/contactus",
            {
                templateUrl:"contactus.html",
                controller:"myCtrl"
            })
            .when("/map",
            {
                templateUrl:"map.html",
                controller:"myCtrl"
            })
            .when("/aboutus",
            {
                templateUrl:"aboutus.html",
                controller:"myCtrl"
            }) ;
    });


