var app = angular.module("myApp", ["ngRoute"]);
    app.config(function($routeProvider)
    {
            $routeProvider
            .when("/rideslide",
            {
                templateUrl:"rideslide.html",
                controller:"myCtrl"
            })
            .when("/rideslide3",
            {
                templateUrl:"rideslide3.html",
                controller:"myCtrl"
            })
            .when("/rideslide4",
            {
                templateUrl:"rideslide4.html",
                controller:"myCtrl"
            })
            .when("/rideslide5",
            {
                templateUrl:"rideslide5.html",
                controller:"myCtrl"
            })
            .when("/rideslide6",
            {
                templateUrl:"rideslide6.html",
                controller:"myCtrl"
            })
            .when("/rideslide7",
            {
                templateUrl:"rideslide7.html",
                controller:"myCtrl"
            })
            .when("/rideslide8",
            {
                templateUrl:"rideslide8.html",
                controller:"myCtrl"
            })
            .when("/rideslide9",
            {
                templateUrl:"rideslide9.html",
                controller:"myCtrl"
            })
            .when("/rideslide10",
            {
                templateUrl:"rideslide10.html",
                controller:"myCtrl"
            })
            .when("/rideslide11",
            {
                templateUrl:"rideslide11.html",
                controller:"myCtrl"
            })
            .when("/information",
            {
                templateUrl:"information.html",
                controller:"myCtrl"
            })
            .when("/information2",
            {
                templateUrl:"information2.html",
                controller:"myCtrl"
            })
            .when("/facilities",
            {
                templateUrl:"facilities.html",
                controller:"myCtrl"
            })
            .when("/food",
            {
                templateUrl:"food.html",
                controller:"myCtrl"
            })
            .when("/contactus",
            {
                templateUrl:"contactus.html",
                controller:"myCtrl"
            })
            .when("/map",
            {
                templateUrl:"map.html",
                controller:"myCtrl"
            })
            .when("/aboutus",
            {
                templateUrl:"aboutus.html",
                controller:"myCtrl"
            }) ;
    });
